# Generated by Django 4.1.7 on 2023-04-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='permission',
            field=models.ManyToManyField(to='api.permission'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ManyToManyField(to='api.profile'),
        ),
    ]
